// Generated by scripts/check-public-api.mjs.
// This file records every local declaration reachable from the XLSX public entry.
// Do not edit by hand.

// --- file: xlsx.d.ts ---
export function autoResize(render: (width: number, height: number) => void | Promise<void>, element: Element, opts?: AutoResizeOptions): () => void;
export interface AutoResizeOptions {
    pauseWhenHidden?: boolean;
}
export interface Border {
    left: BorderEdge | null;
    right: BorderEdge | null;
    top: BorderEdge | null;
    bottom: BorderEdge | null;
    diagonalUp?: BorderEdge | null;
    diagonalDown?: BorderEdge | null;
    horizontal?: BorderEdge | null;
    vertical?: BorderEdge | null;
}
export interface BorderEdge {
    style: string;
    color: string | null;
}
type CanvasViewerRenderMode = 'main' | 'worker';
export interface Cell {
    col: number;
    row: number;
    value: CellValue;
    styleIndex?: number;
    formula?: string;
    showPhonetic?: boolean;
}
export interface CellAddress {
    row: number;
    col: number;
}
export interface CellFill {
    patternType: string;
    fgColor: string | null;
    bgColor: string | null;
    gradient?: GradientFillSpec | null;
}
export interface CellFont {
    bold: boolean;
    italic: boolean;
    underline: boolean;
    strike: boolean;
    size: number;
    color: string | null;
    name: string | null;
    underlineStyle?: string;
    vertAlign?: 'superscript' | 'subscript';
}
export interface CellRange {
    anchor: CellAddress;
    active: CellAddress;
    mode: SelectionMode;
}
interface CellRange__emitterCollision1 {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export type CellValue = {
    type: 'empty';
} | {
    type: 'text';
    text: string;
    runs?: Run[];
    phoneticRuns?: PhoneticRun[];
    phoneticPr?: PhoneticProperties;
} | {
    type: 'number';
    number: number;
} | {
    type: 'bool';
    bool: boolean;
} | {
    type: 'error';
    error: string;
} | {
    type: 'shared';
    si: number;
};
export interface CellXf {
    fontId: number;
    fillId: number;
    borderId: number;
    numFmtId: number;
    alignH: string | null;
    alignV: string | null;
    wrapText: boolean;
    indent?: number;
    textRotation?: number;
    shrinkToFit?: boolean;
    readingOrder?: number;
}
export interface CfIcon {
    iconSet: string;
    iconId: number;
}
export type CfRule = {
    type: 'cellIs';
    operator: string;
    formulas: string[];
    dxfId: number | null;
    priority: number;
} | {
    type: 'expression';
    formula: string;
    dxfId: number | null;
    priority: number;
    stopIfTrue: boolean;
} | {
    type: 'colorScale';
    stops: CfStop[];
    priority: number;
} | {
    type: 'dataBar';
    color: string;
    min: CfValue;
    max: CfValue;
    priority: number;
    gradient: boolean;
} | {
    type: 'top10';
    top: boolean;
    percent: boolean;
    rank: number;
    dxfId: number | null;
    priority: number;
} | {
    type: 'aboveAverage';
    aboveAverage: boolean;
    equalAverage?: boolean;
    stdDev?: number;
    dxfId: number | null;
    priority: number;
} | {
    type: 'iconSet';
    iconSet: string;
    cfvos: CfValue[];
    reverse: boolean;
    priority: number;
    customIcons?: CfIcon[];
} | {
    type: 'other';
    kind: string;
    priority: number;
};
export interface CfStop {
    kind: string;
    value: string | null;
    color: string;
}
export interface CfValue {
    kind: string;
    value: string | null;
}
export interface ChartAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    chart: ChartModel;
}
export interface ChartDataLabelOverride {
    idx: number;
    text: string;
    position?: string;
    fontColor?: string;
    fontSizeHpt?: number;
    fontBold?: boolean;
    labelBox?: ChartLabelBox;
    showVal?: boolean;
    showCatName?: boolean;
    showSerName?: boolean;
    showPercent?: boolean;
    deleted?: boolean;
}
export interface ChartDataPointOverride {
    idx: number;
    color?: string;
    markerSymbol?: string;
    markerSize?: number;
    markerFill?: string;
    markerLine?: string;
    explosion?: number;
}
export interface ChartErrBars {
    dir: string;
    barType: string;
    plus: (number | null)[];
    minus: (number | null)[];
    noEndCap: boolean;
    color?: string;
    lineWidthEmu?: number;
    dash?: string;
}
interface ChartexBoxSeries {
    name: string;
    color?: string | null;
    valuesByCategory: number[][];
    meanMarker: boolean;
    meanLine: boolean;
    showOutliers: boolean;
    showNonoutliers: boolean;
    quartileMethod: string;
}
interface ChartexBoxWhisker {
    categories: string[];
    series: ChartexBoxSeries[];
}
interface ChartexSunburst {
    rows: ChartexSunburstRow[];
}
interface ChartexSunburstRow {
    path: string[];
    size: number;
}
interface ChartLabelBox {
    fill?: string;
    borderColor?: string;
    borderWidthEmu?: number;
}
export interface ChartManualLayout {
    xMode: string;
    yMode: string;
    layoutTarget?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface ChartModel {
    chartType: ChartType;
    title: string | null;
    categories: string[];
    series: ChartSeries[];
    varyColors?: boolean | null;
    showDataLabels: boolean;
    valMin: number | null;
    valMax: number | null;
    catAxisTitle: string | null;
    valAxisTitle: string | null;
    catAxisHidden: boolean;
    valAxisHidden: boolean;
    catAxisLineHidden: boolean;
    valAxisLineHidden: boolean;
    plotAreaBg: string | null;
    chartBg: string | null;
    showLegend: boolean;
    legendPos: 'r' | 'l' | 't' | 'b' | 'tr' | null;
    catAxisCrossBetween: 'between' | 'midCat' | string;
    valAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    catAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    valAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    catAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    titleFontSizeHpt: number | null;
    titleFontColor: string | null;
    titleFontFace: string | null;
    catAxisFontSizeHpt: number | null;
    valAxisFontSizeHpt: number | null;
    catAxisFontColor?: string | null;
    valAxisFontColor?: string | null;
    dataLabelFontSizeHpt: number | null;
    subtotalIndices: number[];
    legendManualLayout?: LegendManualLayout | null;
    valAxisFormatCode?: string | null;
    barGapWidth?: number | null;
    barOverlap?: number | null;
    dataLabelPosition?: string | null;
    dataLabelFontColor?: string | null;
    dataLabelFormatCode?: string | null;
    titleFontBold?: boolean | null;
    catAxisFontBold?: boolean | null;
    valAxisFontBold?: boolean | null;
    catAxisTitleFontSizeHpt?: number | null;
    catAxisTitleFontBold?: boolean | null;
    catAxisTitleFontColor?: string | null;
    valAxisTitleFontSizeHpt?: number | null;
    valAxisTitleFontBold?: boolean | null;
    valAxisTitleFontColor?: string | null;
    catAxisFontFace?: string | null;
    valAxisFontFace?: string | null;
    catAxisTitleFontFace?: string | null;
    valAxisTitleFontFace?: string | null;
    dataLabelFontFace?: string | null;
    legendFontFace?: string | null;
    legendFontColor?: string | null;
    legendFontSizeHpt?: number | null;
    legendFontBold?: boolean | null;
    themeMajorFontLatin?: string | null;
    themeMinorFontLatin?: string | null;
    chartBorderColor?: string | null;
    chartBorderWidthEmu?: number | null;
    catAxisCrosses?: string | null;
    catAxisCrossesAt?: number | null;
    valAxisCrosses?: string | null;
    valAxisCrossesAt?: number | null;
    catAxisLineColor?: string | null;
    catAxisLineWidthEmu?: number | null;
    valAxisLineColor?: string | null;
    valAxisLineWidthEmu?: number | null;
    catAxisFormatCode?: string | null;
    catAxisMin?: number | null;
    catAxisMax?: number | null;
    titleManualLayout?: ChartManualLayout | null;
    plotAreaManualLayout?: ChartManualLayout | null;
    scatterStyle?: string | null;
    radarStyle?: string | null;
    secondaryValAxis?: SecondaryValueAxis | null;
    date1904?: boolean;
    holeSize?: number | null;
    firstSliceAngle?: number | null;
    dispBlanksAs?: string | null;
    valAxisMajorGridlines?: boolean | null;
    catAxisMajorGridlines?: boolean | null;
    valAxisGridlineColor?: string | null;
    valAxisGridlineWidthEmu?: number | null;
    catAxisGridlineColor?: string | null;
    catAxisGridlineWidthEmu?: number | null;
    valAxisMinorGridlines?: boolean | null;
    valAxisMajorUnit?: number | null;
    valAxisMinorUnit?: number | null;
    valAxisLogBase?: number | null;
    valAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisTickLabelPos?: string | null;
    valAxisTickLabelPos?: string | null;
    catAxisLabelRotation?: number | null;
    stockHiLowLines?: boolean | null;
    stockHiLowLineColor?: string | null;
    stockUpDownBars?: boolean | null;
    chartexBox?: ChartexBoxWhisker | null;
    chartexSunburst?: ChartexSunburst | null;
    chartexAccents?: string[] | null;
}
export interface ChartSeries {
    name: string;
    color: string | null;
    values: (number | null)[];
    dataPointColors?: (string | null)[] | null;
    dataLabelColors?: (string | null)[] | null;
    labelColor?: string | null;
    seriesType?: string | null;
    useSecondaryAxis?: boolean | null;
    categories?: string[] | null;
    showMarker?: boolean | null;
    valFormatCode?: string | null;
    markerSymbol?: string | null;
    markerSize?: number | null;
    markerFill?: string | null;
    markerLine?: string | null;
    dataPointOverrides?: ChartDataPointOverride[] | null;
    dataLabelOverrides?: ChartDataLabelOverride[] | null;
    seriesDataLabels?: ChartSeriesDataLabels | null;
    errBars?: ChartErrBars[] | null;
    bubbleSizes?: (number | null)[] | null;
    smooth?: boolean | null;
    trendLines?: ChartTrendline[] | null;
    lineHidden?: boolean | null;
}
export interface ChartSeriesDataLabels {
    showVal: boolean;
    showCatName: boolean;
    showSerName: boolean;
    showPercent: boolean;
    position?: string;
    fontColor?: string;
    formatCode?: string;
    fontBold?: boolean;
    fontSizeHpt?: number;
    labelBox?: ChartLabelBox;
    showLeaderLines?: boolean;
    leaderLineColor?: string;
    leaderLineWidthEmu?: number;
}
interface ChartTrendline {
    trendlineType: string;
    order?: number | null;
    period?: number | null;
    forward?: number | null;
    backward?: number | null;
    intercept?: number | null;
    dispRSqr?: boolean | null;
    dispEq?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
}
type ChartType = 'line' | 'stackedLine' | 'stackedLinePct' | 'clusteredBar' | 'clusteredBarH' | 'stackedBar' | 'stackedBarH' | 'stackedBarPct' | 'stackedBarHPct' | 'area' | 'stackedArea' | 'stackedAreaPct' | 'pie' | 'doughnut' | 'scatter' | 'bubble' | 'radar' | 'waterfall' | 'stock' | 'boxWhisker' | 'sunburst' | string;
export interface ConditionalFormat {
    sqref: CellRange__emitterCollision1[];
    rules: CfRule[];
}
export type DataLabelOverride = ChartDataLabelOverride;
export type DataPointOverride = ChartDataPointOverride;
export interface DataValidation {
    sqref: string;
    validationType?: string;
    operator?: string;
    formula1?: string;
    formula2?: string;
    allowBlank?: boolean;
    promptTitle?: string;
    prompt?: string;
    errorTitle?: string;
    errorMessage?: string;
}
export interface DefinedName {
    name: string;
    formula: string;
}
export interface Duotone {
    clr1: string;
    clr2: string;
}
export interface Dxf {
    font: CellFont | null;
    fill: CellFill | null;
    border: Border | null;
    numFmt?: NumFmt | null;
}
export type ErrBars = ChartErrBars;
type ExtensibleLiteral<Known extends string> = Known | (string & Record<never, never>);
export interface FindHighlightColors {
    match?: string;
    active?: string;
}
export interface FindMatch<Loc = unknown> {
    matchIndex: number;
    text: string;
    location: Loc;
}
export interface FindMatchesOptions {
    caseSensitive?: boolean;
}
export interface GradientFillSpec {
    gradientType: string;
    degree: number;
    left: number;
    right: number;
    top: number;
    bottom: number;
    stops: {
        position: number;
        color: string;
    }[];
}
export type HiddenSheetMode = 'show' | 'skip' | 'dim';
export interface Hyperlink {
    col: number;
    row: number;
    url: string | null;
    location?: string | null;
    display?: string | null;
}
export type HyperlinkTarget = {
    kind: 'external';
    url: string;
} | {
    kind: 'internal';
    ref: string;
    slideIndex?: number;
};
export interface ImageAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    editAs?: string;
    nativeExtCx: number;
    nativeExtCy: number;
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
}
export function isOoxmlDecodedImageLimitError(error: unknown): error is OoxmlDecodedImageLimitError;
export interface LegendManualLayout {
    xMode: string;
    yMode: string;
    x: number;
    y: number;
    w: number;
    h: number;
}
export interface LoadOptions extends LoadOptions__emitterCollision1 {
    mode?: 'main' | 'worker';
}
interface LoadOptions__emitterCollision1 {
    useGoogleFonts?: boolean;
    password?: string;
    wasmUrl?: string | URL;
    maxZipEntryBytes?: number;
    resourceLimits?: OoxmlResourceLimits;
    debug?: boolean;
    onResourceMetrics?: (metrics: OoxmlResourceMetrics) => void;
    workerTimeoutMs?: number;
    math?: MathRenderer;
}
export type ManualLayout = ChartManualLayout;
interface MathAccent {
    kind: 'accent';
    char: string;
    base: MathNode[];
}
interface MathArray {
    kind: 'array';
    rows: MathNode[][][];
    align: 'eq' | 'center' | 'left';
}
interface MathBar {
    kind: 'bar';
    pos: 'top' | 'bot';
    base: MathNode[];
}
interface MathBorderBox {
    kind: 'borderBox';
    hideTop?: boolean;
    hideBot?: boolean;
    hideLeft?: boolean;
    hideRight?: boolean;
    strikeH?: boolean;
    strikeV?: boolean;
    strikeBltr?: boolean;
    strikeTlbr?: boolean;
    base: MathNode[];
}
interface MathBox {
    kind: 'box';
    base: MathNode[];
}
interface MathDelimiter {
    kind: 'delimiter';
    begChar: string;
    endChar: string;
    items: MathNode[][];
}
interface MathFraction {
    kind: 'fraction';
    num: MathNode[];
    den: MathNode[];
    bar?: boolean;
}
interface MathFunc {
    kind: 'func';
    name: MathNode[];
    arg: MathNode[];
}
interface MathGroup {
    kind: 'group';
    items: MathNode[];
}
interface MathGroupChr {
    kind: 'groupChr';
    char: string;
    pos: 'top' | 'bot';
    base: MathNode[];
}
interface MathLimit {
    kind: 'limit';
    base: MathNode[];
    lower?: MathNode[];
    upper?: MathNode[];
}
interface MathNary {
    kind: 'nary';
    op: string;
    limLoc?: string;
    sub?: MathNode[];
    sup?: MathNode[];
    body: MathNode[];
}
type MathNode = MathRun | MathFraction | MathScript | MathNary | MathDelimiter | MathRadical | MathLimit | MathArray | MathGroupChr | MathBar | MathAccent | MathFunc | MathGroup | MathPhant | MathSPre | MathBox | MathBorderBox;
interface MathPhant {
    kind: 'phant';
    show: boolean;
    zeroWid?: boolean;
    zeroAsc?: boolean;
    zeroDesc?: boolean;
    base: MathNode[];
}
interface MathRadical {
    kind: 'radical';
    index?: MathNode[];
    radicand: MathNode[];
}
interface MathRenderer {
    loadMathJax(): Promise<void>;
    mathMLToSvg(mathml: string): Promise<MathSvg>;
}
interface MathRun {
    kind: 'run';
    text: string;
    style: MathStyle;
}
interface MathScript {
    kind: 'sup' | 'sub' | 'subSup';
    base: MathNode[];
    sup?: MathNode[];
    sub?: MathNode[];
}
interface MathSPre {
    kind: 'sPre';
    sub: MathNode[];
    sup: MathNode[];
    base: MathNode[];
}
type MathStyle = 'roman' | 'italic' | 'bold' | 'boldItalic';
interface MathSvg {
    svg: string;
    widthEm: number;
    ascentEm: number;
    descentEm: number;
}
export interface MergeCell {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export interface NumFmt {
    numFmtId: number;
    formatCode: string;
}
export class OoxmlDecodedImageLimitError extends RangeError {
    readonly metric: OoxmlDecodedImageLimitMetric;
    readonly limit: number;
    readonly observed: number;
    readonly code: 'ooxml-decoded-image-limit';
    constructor(metric: OoxmlDecodedImageLimitMetric, limit: number, observed: number);
}
export type OoxmlDecodedImageLimitMetric = 'image-pixels' | 'active-decoded-bytes';
export class OoxmlError extends Error {
    readonly code: OoxmlErrorCode;
    constructor(code: OoxmlErrorCode, message: string);
}
export type OoxmlErrorCode = 'encrypted' | 'invalid-password' | 'unsupported-encryption' | 'legacy-binary-format' | 'not-ooxml';
export type OoxmlErrorSource = 'container' | 'zip-part' | 'parser' | 'serializer' | 'layout' | 'renderer' | 'worker';
export type OoxmlErrorStage = 'container' | 'decompression' | 'parsing' | 'serialization' | 'layout' | 'rendering' | 'worker';
export type OoxmlFormat = 'docx' | 'xlsx' | 'pptx';
export type OoxmlResourceLimit = number | null;
export class OoxmlResourceLimitError extends Error {
    readonly code: 'ooxml-resource-limit';
    readonly details: OoxmlResourceLimitErrorDetails;
    constructor(message: string, details: OoxmlResourceLimitErrorDetails);
}
export interface OoxmlResourceLimitErrorDetails {
    readonly stage: OoxmlErrorStage;
    readonly violation: OoxmlResourceViolation;
}
export interface OoxmlResourceLimits {
    maxArchiveEntryBytes?: OoxmlResourceLimit;
    maxTotalInflatedBytes?: OoxmlResourceLimit;
    maxArchiveEntries?: OoxmlResourceLimit;
}
export type OoxmlResourceMetric = ExtensibleLiteral<'declared-inflated-bytes' | 'actual-inflated-bytes' | 'entry-count' | 'central-directory-bytes' | 'distinct-inflated-bytes' | 'bytes' | 'depth' | 'projected-bytes'>;
export interface OoxmlResourceMetrics {
    readonly schemaVersion: 1;
    readonly scope: 'load' | 'session';
    readonly format: OoxmlFormat;
    readonly mode: 'main' | 'worker' | 'node';
    readonly status: 'ok' | 'error';
    readonly sourceBytes?: number;
    readonly elapsedMs: number;
    readonly policy: Readonly<OoxmlResourcePolicySnapshot>;
    readonly usage?: OoxmlResourceUsageSnapshot;
    readonly checkpoints: readonly OoxmlResourceMetricsCheckpoint[];
    readonly outcome?: Readonly<Record<string, number>>;
    readonly error?: Readonly<{
        readonly code?: string;
        readonly stage?: string;
        readonly resource?: string;
        readonly metric?: string;
    }>;
}
export interface OoxmlResourceMetricsCheckpoint {
    readonly name: string;
    readonly elapsedMs: number;
    readonly usage?: OoxmlResourceUsageSnapshot;
}
export type OoxmlResourceName = ExtensibleLiteral<'archive' | 'archive-entry' | 'xml-event' | 'xml-context' | 'xml-tree' | 'worksheet-row' | 'worksheet-shell'>;
export interface OoxmlResourcePolicySnapshot {
    readonly maxArchiveEntryBytes: number | null;
    readonly maxTotalInflatedBytes: number | null;
    readonly maxArchiveEntries: number | null;
}
export interface OoxmlResourceUsageSnapshot {
    readonly archiveEntryCount: number;
    readonly declaredInflatedBytes: number;
    readonly largestInflatedEntryBytes?: number;
    readonly distinctInflatedBytes: number;
    readonly operationInflatedBytes: number;
}
export interface OoxmlResourceViolation {
    readonly format: OoxmlFormat;
    readonly operation: string;
    readonly resource: OoxmlResourceName;
    readonly metric: OoxmlResourceMetric;
    readonly part?: string;
    readonly limit: number;
    readonly observed: number;
    readonly configurable: boolean;
    readonly usage: OoxmlResourceUsageSnapshot;
}
export function openExternalHyperlink(url: string, allowed?: readonly string[], win?: Pick<Window, 'open'> | undefined): boolean;
export interface OutlinePr {
    summaryBelow: boolean;
    summaryRight: boolean;
}
export interface ParsedWorkbook {
    workbook: Workbook;
    styles: Styles;
    sharedStrings: SharedString[];
}
export type PathCmd = {
    op: 'moveTo';
    x: number;
    y: number;
} | {
    op: 'lineTo';
    x: number;
    y: number;
} | {
    op: 'cubicBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    x3: number;
    y3: number;
} | {
    op: 'quadBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
} | {
    op: 'arcTo';
    wr: number;
    hr: number;
    stAng: number;
    swAng: number;
} | {
    op: 'close';
};
export interface PathInfo {
    w: number;
    h: number;
    commands: PathCmd[];
}
export type PhoneticAlignment = 'left' | 'center' | 'distributed' | 'noControl';
export interface PhoneticProperties {
    fontId: number;
    type?: PhoneticType;
    alignment?: PhoneticAlignment;
}
export interface PhoneticRun {
    sb: number;
    eb: number;
    text: string;
}
export type PhoneticType = 'fullwidthKatakana' | 'halfwidthKatakana' | 'Hiragana' | 'noConversion';
export type PivotCacheSource = {
    kind: 'worksheet';
    sheet?: string;
    reference?: string;
    name?: string;
    relationshipId?: string;
} | {
    kind: 'external';
} | {
    kind: 'consolidation';
} | {
    kind: 'scenario';
};
export interface PivotDataField {
    field: number;
    subtotal?: string;
    rawSubtotal?: string;
    name?: string;
}
export interface PivotDiagnostic {
    part: string;
    reason: {
        kind: 'unreadableWorksheetRelationships';
    } | {
        kind: 'malformedWorksheetRelationships';
    } | {
        kind: 'malformedPivotRelationship';
    } | {
        kind: 'externalPivotRelationship';
    } | {
        kind: 'unreadablePart';
    } | {
        kind: 'malformedXml';
    } | {
        kind: 'missingIdentity';
    } | {
        kind: 'invalidLocation';
    };
}
export interface PivotLocation extends CellRange__emitterCollision1 {
    firstHeaderRow: number;
    firstDataRow: number;
    firstDataCol: number;
}
export type PivotMetadataStatus = {
    state: 'complete';
} | {
    state: 'partial';
    reasons: PivotPartialReason[];
};
export interface PivotPageField {
    field: number;
    item?: number;
    name?: string;
}
export type PivotPartialReason = {
    kind: 'missingCacheRelationship';
} | {
    kind: 'malformedCacheRelationships';
} | {
    kind: 'unreadableCacheRelationships';
} | {
    kind: 'externalCacheRelationship';
} | {
    kind: 'ambiguousCacheRelationship';
} | {
    kind: 'unreadableCacheDefinition';
} | {
    kind: 'malformedCacheDefinition';
} | {
    kind: 'malformedField';
    field: string;
} | {
    kind: 'unsupportedCacheSource';
    sourceType: string;
} | {
    kind: 'unresolvedWorksheetSourceRelationship';
} | {
    kind: 'unsupportedSemanticFeature';
    feature: string;
};
export interface PivotTableMetadata {
    name: string;
    cacheId: number;
    location: PivotLocation;
    rowFields: number[];
    columnFields: number[];
    pageFields: PivotPageField[];
    dataFields: PivotDataField[];
    refreshOnLoad?: boolean;
    cacheInvalid?: boolean;
    cacheDefinitionPart?: string;
    cacheSource?: PivotCacheSource;
    status: PivotMetadataStatus;
    extensionUris?: string[];
}
export interface RenderViewportOptions {
    width?: number;
    height?: number;
    dpr?: number;
    defaultFontFamily?: string;
    defaultFontSize?: number;
    scrollOffsetX?: number;
    scrollOffsetY?: number;
    freezeRows?: number;
    freezeCols?: number;
    cellScale?: number;
    loadedImages?: Map<string, CanvasImageSource | null>;
    fetchImage?: (path: string, mimeType: string) => Promise<Blob>;
    onTextRun?: (info: XlsxTextRunInfo) => void;
    selectedRowRange?: {
        start: number;
        end: number;
        strong: boolean;
    } | null;
    selectedColRange?: {
        start: number;
        end: number;
        strong: boolean;
    } | null;
}
export type ResolvedList = {
    kind: 'values';
    values: string[];
} | {
    kind: 'formula';
    formula: string;
};
export function resolveSharedStrings(ws: Worksheet, sharedStrings: SharedString[]): Worksheet;
export interface Row {
    index: number;
    height: number | null;
    cells: Cell[];
    outlineLevel?: number;
    collapsed?: boolean;
    hidden?: boolean;
}
export interface Run {
    text: string;
    font?: RunFont;
}
export interface RunFont {
    bold: boolean;
    italic: boolean;
    underline: boolean;
    strike: boolean;
    size?: number;
    color?: string | null;
    name?: string | null;
    underlineStyle?: string;
    vertAlign?: 'superscript' | 'subscript';
}
interface SecondaryValueAxis {
    min: number | null;
    max: number | null;
    title: string | null;
    hidden: boolean;
    formatCode?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineHidden: boolean;
    majorTickMark: string;
    majorUnit?: number | null;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontColor?: string | null;
}
export type SelectionMode = 'cells' | 'rows' | 'cols' | 'all';
export type SeriesDataLabels = ChartSeriesDataLabels;
export interface ShapeAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    editAs?: string;
    nativeExtCx: number;
    nativeExtCy: number;
    shapes: ShapeInfo[];
}
export type ShapeGeom = {
    type: 'preset';
    name: string;
    adj?: (number | null)[];
} | {
    type: 'custom';
    paths: PathInfo[];
} | {
    type: 'image';
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
};
export interface ShapeInfo {
    x: number;
    y: number;
    w: number;
    h: number;
    rot: number;
    flipH?: boolean;
    flipV?: boolean;
    fillColor?: string;
    strokeColor?: string;
    strokeWidth: number;
    geom: ShapeGeom;
    text?: ShapeText;
}
export interface ShapeParagraph {
    align: string;
    rtl?: boolean;
    marL?: number;
    marR?: number;
    indent?: number;
    spaceLine?: SpaceLine | null;
    runs: ShapeTextRun[];
}
export interface ShapeText {
    anchor: string;
    wrap: string;
    autoFit?: string;
    fontScale?: number | null;
    lnSpcReduction?: number | null;
    lIns: number;
    tIns: number;
    rIns: number;
    bIns: number;
    paragraphs: ShapeParagraph[];
}
export type ShapeTextRun = {
    type: 'text';
    text: string;
    bold: boolean;
    italic: boolean;
    size: number;
    color?: string;
    fontFace?: string;
    fontFaceEa?: string;
    fontFaceCs?: string;
} | {
    type: 'break';
} | {
    type: 'math';
    nodes: MathNode[];
    display: boolean;
    fontSize?: number;
    color?: string;
};
export interface SharedString {
    text: string;
    runs?: Run[];
    phoneticRuns?: PhoneticRun[];
    phoneticPr?: PhoneticProperties;
}
export interface SheetMeta {
    name: string;
    sheetId: number;
    rId: string;
    tabColor?: string | null;
    visibility?: 'hidden' | 'veryHidden';
}
export type SheetVisibility = 'visible' | 'hidden' | 'veryHidden';
export interface SlicerAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    caption: string;
    items: SlicerItem[];
    style?: SlicerStyle;
}
export interface SlicerElementStyle {
    fontColor?: string;
    fontSize?: number;
    fontBold?: boolean;
    fontFamily?: string;
    fillColor?: string;
    borderColor?: string;
}
export interface SlicerItem {
    name: string;
    selected: boolean;
}
export interface SlicerStyle {
    whole?: SlicerElementStyle;
    header?: SlicerElementStyle;
    selectedItemWithData?: SlicerElementStyle;
    unselectedItemWithData?: SlicerElementStyle;
}
type SpaceLine = {
    type: 'pct';
    val: number;
} | {
    type: 'pts';
    val: number;
};
export interface Sparkline {
    row: number;
    col: number;
    values: (number | null)[];
}
export interface SparklineGroup {
    kind: 'line' | 'column' | 'stem';
    markers: boolean;
    high: boolean;
    low: boolean;
    first: boolean;
    last: boolean;
    negative: boolean;
    displayXAxis: boolean;
    displayEmptyCellsAs: string;
    minAxisType: string;
    maxAxisType: string;
    manualMin?: number;
    manualMax?: number;
    lineWeight: number;
    colorSeries?: string;
    colorNegative?: string;
    colorAxis?: string;
    colorMarkers?: string;
    colorFirst?: string;
    colorLast?: string;
    colorHigh?: string;
    colorLow?: string;
    sparklines: Sparkline[];
}
export interface Styles {
    fonts: CellFont[];
    fills: CellFill[];
    borders: Border[];
    cellXfs: CellXf[];
    numFmts: NumFmt[];
    dxfs: Dxf[];
}
export interface TableColumnInfo {
    dataDxfId?: number;
    headerRowDxfId?: number;
    totalsRowDxfId?: number;
}
export interface TableInfo {
    range: CellRange__emitterCollision1;
    styleName: string;
    headerRowCount: number;
    totalsRowCount: number;
    showRowStripes: boolean;
    showColumnStripes: boolean;
    showFirstColumn: boolean;
    showLastColumn: boolean;
    accentColor: string;
    isCustom?: boolean;
    wholeTableDxf?: number;
    headerRowDxf?: number;
    totalRowDxf?: number;
    firstColumnDxf?: number;
    lastColumnDxf?: number;
    band1HorizontalDxf?: number;
    band2HorizontalDxf?: number;
    columns: TableColumnInfo[];
}
export interface ViewportRange {
    row: number;
    col: number;
    rows: number;
    cols: number;
}
export type WireRenderViewportOptions = Omit<RenderViewportOptions, 'onTextRun' | 'loadedImages' | 'fetchImage'> & {
    sizeOverrides?: WireSizeOverrides;
};
export interface WireSizeOverrides {
    rows?: Record<number, number | null>;
    cols?: Record<number, number | null>;
}
export interface Workbook {
    sheets: SheetMeta[];
    date1904?: boolean;
    parseError?: string;
}
export interface Worksheet {
    name: string;
    rows: Row[];
    colWidths: Record<number, number>;
    rowHeights: Record<number, number>;
    colOutlineLevels?: Record<number, number>;
    colCollapsed?: Record<number, boolean>;
    colHidden?: Record<number, boolean>;
    defaultColWidth: number;
    defaultRowHeight: number;
    mergeCells: MergeCell[];
    freezeRows: number;
    freezeCols: number;
    conditionalFormats: ConditionalFormat[];
    images: ImageAnchor[];
    charts: ChartAnchor[];
    shapeGroups?: ShapeAnchor[];
    showZeros?: boolean;
    showGridlines?: boolean;
    rightToLeft?: boolean;
    outlinePr?: OutlinePr;
    tabColor?: string | null;
    autoFilter?: CellRange__emitterCollision1 | null;
    hyperlinks?: Hyperlink[];
    commentRefs?: string[];
    comments?: XlsxComment[];
    dataValidations?: DataValidation[];
    definedNames?: DefinedName[];
    tables?: TableInfo[];
    slicers?: SlicerAnchor[];
    pivotTables?: PivotTableMetadata[];
    pivotDiagnostics?: PivotDiagnostic[];
    sparklineGroups?: SparklineGroup[];
    defaultFontFamily?: string;
    defaultFontSize?: number;
    date1904?: boolean;
    parseError?: string;
}
export type XlsxChartSeries = ChartSeries;
export interface XlsxComment {
    cellRef: string;
    author?: string;
    text: string;
}
export interface XlsxMatchLocation {
    sheet: number;
    sheetName: string;
    ref: string;
    row: number;
    col: number;
}
export interface XlsxScrollToCellOptions {
    readonly align?: 'nearest' | 'start' | 'center' | 'end';
}
export class XlsxSheetViewer implements ZoomableViewer {
    readonly canvasElement: HTMLCanvasElement;
    static fromWorkbook(canvasElement: HTMLCanvasElement, workbook: XlsxWorkbook, options?: Omit<XlsxSheetViewerOptions, keyof LoadOptions__emitterCollision1>): Omit<XlsxSheetViewer, 'load'>;
    constructor(canvasElement: HTMLCanvasElement, options?: XlsxSheetViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    get sheetIndex(): number;
    get sheetCount(): number;
    get sheetNames(): string[];
    goToSheet(index: number): Promise<void>;
    nextSheet(): Promise<void>;
    prevSheet(): Promise<void>;
    getViewportOffset(): XlsxViewportOffset;
    setViewportOffset(offset: XlsxViewportOffset): Promise<void>;
    scrollToCell(ref: string, options?: XlsxScrollToCellOptions): Promise<void>;
    relayout(): Promise<void>;
    getScale(): number;
    setScale(scale: number): void;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    getCellAt(clientX: number, clientY: number): CellAddress | null;
    get selection(): CellRange | null;
    select(ref: string): void;
    setSelectionColor(color: string): void;
    setHiddenSheetMode(mode: HiddenSheetMode): Promise<void>;
    get hiddenSheetMode(): HiddenSheetMode;
    get visibleSheetCount(): number;
    findText(query: string, options?: FindMatchesOptions): Promise<FindMatch<XlsxMatchLocation>[]>;
    findNext(): Promise<FindMatch<XlsxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<XlsxMatchLocation> | null>;
    clearFind(): void;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    destroy(): void;
    private __privatePresence;
}
export interface XlsxSheetViewerOptions extends LoadOptions__emitterCollision1 {
    cellScale?: number;
    resizable?: boolean;
    zoomMin?: number;
    zoomMax?: number;
    onScaleChange?: (scale: number) => void;
    onReady?: (sheetNames: string[]) => void;
    onSheetChange?: (index: number, total: number) => void;
    onError?: (err: Error) => void;
    onSelectionChange?: (selection: CellRange | null) => void;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
    selectionColor?: string;
    findHighlightColors?: FindHighlightColors;
    mode?: 'main' | 'worker';
    hiddenSheetMode?: HiddenSheetMode;
    onViewportChange?: (offset: XlsxViewportOffset) => void;
}
export interface XlsxTextRunInfo {
    sheetName: string;
    cellRef: string;
    text: string;
    x: number;
    y: number;
    width: number;
    height: number;
    row: number;
    col: number;
}
export class XlsxViewer extends XlsxViewerEngine {
    static fromWorkbook(container: HTMLElement, workbook: XlsxWorkbook, opts?: Omit<XlsxViewerOptions, keyof LoadOptions__emitterCollision1>): Omit<XlsxViewer, 'load'>;
    constructor(container: HTMLElement, opts?: XlsxViewerOptions);
}
class XlsxViewerEngine implements ZoomableViewer {
    constructor(container: HTMLElement, opts: XlsxViewerOptions | XlsxSheetViewerOptions | undefined, mount: XlsxViewerMount);
    load(source: string | ArrayBuffer): Promise<void>;
    showSheet(index: number): Promise<void>;
    get sheetIndex(): number;
    get sheetCount(): number;
    goToSheet(index: number): Promise<void>;
    nextSheet(): Promise<void>;
    prevSheet(): Promise<void>;
    getViewportOffset(): XlsxViewportOffset;
    setViewportOffset(offset: XlsxViewportOffset): Promise<void>;
    relayout(): Promise<void>;
    scrollToCell(ref: string, options?: XlsxScrollToCellOptions): Promise<void>;
    getCellAt(clientX: number, clientY: number): CellAddress | null;
    get selection(): CellRange | null;
    select(ref: string): void;
    setSelectionColor(color: string): void;
    setHiddenSheetMode(mode: HiddenSheetMode): Promise<void>;
    get hiddenSheetMode(): HiddenSheetMode;
    get visibleSheetCount(): number;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<XlsxMatchLocation>[]>;
    findNext(): Promise<FindMatch<XlsxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<XlsxMatchLocation> | null>;
    clearFind(): void;
    setScale(scale: number): void;
    getScale(): number;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    get sheetNames(): string[];
    get canvasElement(): HTMLCanvasElement;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    destroy(): void;
    private __privatePresence;
}
type XlsxViewerMount = {
    readonly kind: 'composite';
} | {
    readonly kind: 'sheet';
    readonly canvas: HTMLCanvasElement;
    readonly mode: CanvasViewerRenderMode;
};
export interface XlsxViewerOptions extends XlsxSheetViewerOptions {
    showZoomSlider?: boolean;
}
export interface XlsxViewportOffset {
    readonly x: number;
    readonly y: number;
}
export class XlsxWorkbook {
    get mode(): 'main' | 'worker';
    static load(source: string | ArrayBuffer, opts?: LoadOptions): Promise<XlsxWorkbook>;
    get sheetNames(): string[];
    get sheetCount(): number;
    get tabColors(): (string | null)[];
    sheetVisibility(sheetIndex: number): SheetVisibility;
    isHidden(sheetIndex: number): boolean;
    getWorksheet(sheetIndex: number): Promise<Worksheet>;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getImage(imagePath: string, mimeType: string): Promise<Blob>;
    toMarkdown(): Promise<string>;
    resolveValidationList(sheetIndex: number, formula1: string | undefined): Promise<ResolvedList>;
    cellText(ws: Worksheet, cell: Cell): string;
    renderViewport(target: HTMLCanvasElement | OffscreenCanvas, sheetIndex: number, viewport: ViewportRange, opts?: RenderViewportOptions): Promise<void>;
    renderViewportToBitmap(sheetIndex: number, viewport: ViewportRange, opts: WireRenderViewportOptions & {
        width: number;
        height: number;
    }): Promise<ImageBitmap>;
    destroy(): void;
    private __privatePresence;
    private constructor();
}
interface ZoomableViewer {
    getScale(): number;
    setScale(scale: number): void | Promise<void>;
    zoomIn(): void | Promise<void>;
    zoomOut(): void | Promise<void>;
    fitWidth(): void | Promise<void>;
    fitPage(): void | Promise<void>;
}
